spring:
  profiles:
    active: dev
---
#开发环境配置
spring:
  profiles: dev
  application:
    name: microservicecloud-config-mingqian-dev

---
#测试环境配置
spring:
  profiles: test
  application:
    name: microservicecloud-config-mingqian-test
    



