spring:
  profles:
    active: -dev


---
spring:
  profles: dev #开发环境
    active:
  application:
    name: microservicecloud-config-mingqian-dev


---

spring:
  profles: test #测试环境
    active:
  application:
    name: microservicecloud-config-mingqian-test